spring.application.name=store-gateway
server.port=8080

# URLs des microservices internes
products.service.url=http://localhost:8081
checkout.service.url=http://localhost:8082
core.service.url=http://localhost:8000


