server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Pour une Single Page App (React, Vite, etc.)
    location / {
        try_files $uri /index.html;
    }

    # Si plus tard tu appelles un backend via /api, on adaptera cette partie
    # location /api/ {
    #     proxy_pass http://core-service:8080;
    # }
}
